### ISSUE TITLE
Project does not play well with bower

### ISSUE THREAD

**Issue by nleclerc** [CreateJS/PreloadJS#102]
Using preloadjs with bower might cause problems because of 2 different issues:
- git tags do not use appropriate syntax: ie. release_v0.4.1 instead of v0.4.1. So bower cannot properly handle versions.
- script file names include version number, which is going to break if installed version does not match exactly expected version.

This does not allow any [advanced range syntax](https://github.com/npm/node-semver#advanced-range-syntax) and thus is pretty inconvenient.

If you really need the release_ tags then i guess just adding the vX.X.X should do the trick.

**Comment by anouar-hamed** [comment]
what's the point of using bower if we end up with a script file containing the version ex:'preloadjs-0.6.0.min.js' ? When upgrading with bower, my app will break and i will have to manually change my import. The script file shouldn't be like this? 'preloadjs.min.js'?

**Comment by nleclerc** [comment]
Yeah, that part hasn't been fixed.
I guess it'll require another open issue.

**Comment by lannymcnie** [comment]
@anouar-hamed 
You could reference the NEXT version, which is the very latest code. I don't know that updating to different code is desirable -- that has a pretty good chance of breaking your app. Versions are updated about 1-2 times per year, so its a pretty limited edge case that you will get a new version. In that case there are likely to be breaking changes, so you would have updating pains either way.

Pulling in bower code is useful for quick testing, but I would recommend copying into your app folder structure, so that you are working against a known codebase.

**Comment by gskinner** [comment]
I agree with Lanny. Specify NEXT if you want the latest and greatest. The last thing we want to do is have someone pull down a version, and have it inject bugs into their project without them being aware of it.

**Comment by nleclerc** [comment]
Well, bower configuration and [semver](http://semver.org/) are supposed to prevent this kind of problems.
Also, it works with all the other projects on the planet so it can't be that terrible.
