### ISSUE TITLE
PreloadJS 0.6.0 cannot load sound files on iOS 8

### ISSUE THREAD

**Issue by vendornet** [CreateJS/PreloadJS#121]
The new version of PreloadJS 0.6.0 cannot load sound files on iOS 8.1.3 (Safari, Native browser). A fast example to test is to open the official PreloadJS page on iPhone and try to click on the example 'PRELOADJS IN ACTION' - http://www.createjs.com/#!/PreloadJS . Click only on the button 'Audio' and the browser will stuck on Loading...

**Comment by lannymcnie** [comment]
This may be due to the fact that there are mobile restrictions that require all audio to be played with a user-event, such as a click. In this example, the preload is kicked off with the click, but the actual audio playback happens when the file loads asynchronously.

Check out the mobile safe approach tutorial: http://createjs.com/tutorials/Mobile%20Safe%20Approach/

**Comment by vendornet** [comment]
Hi @lannymcnie, the problem is that preloadjs is not loading the file at all. If you have a queue, the whole queue will be blocked by the sound file and will not load.

**Comment by lannymcnie** [comment]
OK, we can check it out. Thanks!

**Comment by lannymcnie** [comment]
@vendornet I tested the MediaGrid with the latest libs, and it looks like it works. We have made some critical fixes between Sound and Preload, so hopefully this has been addressed. Feel free to grab the latest of both libraries from GitHub (the NEXT versions), and let me know if the problem persists.

**Comment by lannymcnie** [comment]
Closing for now. Please re-open if this persists.

**Comment by Manojraj** [comment]
The problem still exists. I tested with the latest version available in github.... When i opened "MediaGrid.html" file (available in examples folder) in my iOS mobile(both safari and chrome) the sound doesn't load and the queue freezes for a 10 seconds trying to load the sound file and shows the error :( and then proceed with the queue...

**Comment by Manojraj** [comment]
When i commented out the following code in "MediaGrid.html" init(), sound is loaded in iOS.. It works fine...

preload.installPlugin(createjs.Sound);

**Comment by lannymcnie** [comment]
@Manojraj PreloadJS *can* load audio without SoundJS, but it is limited to loading HTMLAudioElement items, and has no mechanism to play them. If HTML audio is failing to play using SoundJS it is possible the audio can not be loaded with XHR. You can get around this by forcing the HTMLAudioPlugin to be used instead of the WebAudioPlugin.

```javascript
// Run this before you play any audio, otherwise it uses the default, which is WebAudio first.
createjs.Sound.registerPlugins([createjs.HTMLAudioPlugin]);
```
