### ISSUE TITLE
SpriteSheetLoader with callback uses JSONLoader instead of JSONPLoader

### ISSUE THREAD

**Issue by Xakaloz** [CreateJS/PreloadJS#153]
When i want to load a spritesheet using a JSONP file defining a callback to the LoadItem, SpriteSheetLoader uses JSONLoader instead of JSONPLoader : 

loader.loadFile({src:"images/assets_atlas_.json", callback: "maps", type:"spritesheet", id:"assets_atlas_"}, true);

I had to modify the line 6979 in the p._createRequest method in preloadjs-0.6.1.combined.js : 

if (callback != null && callback instanceof Function) {

to

if (callback != null) {

**Comment by wdamien** [comment]
Can you post some sample source that reproduces the issue?  Thanks!

**Comment by Xakaloz** [comment]
Sorry, my comment was posted accidentally uncomplete :)

**Comment by lannymcnie** [comment]
The SpriteSheetLoader works like most of the other loaders. If there is a `callback` property on the loadItem, it will use JSONP instead.

```javascript
var queue = new createjs.LoadQueue();
queue.loadFile({ src:"spritesheet.json", type:"spritesheet", callback:"JSONCallback" });
```

**Comment by Xakaloz** [comment]
No because you pass as string in the callback parameter and p._createRequest methods wants a Function : 
if (callback != null && callback instanceof Function) {

**Comment by lannymcnie** [comment]
Yeah, that looks like a bug. So you _should_ be able to load via JSONP, but currently you can not. I have changed the status of this question to a verified bug. 

Since this is an easy fix, I made the change, and committed it to GitHub. The NEXT version of the min and combined libs has the fix.

Thanks for the report. Let me know if you have further issues.
