### ISSUE TITLE
ReferenceError: _this is not defined

### ISSUE THREAD

**Issue by attenzione** [CreateJS/PreloadJS#196]
seems typo error:
https://github.com/CreateJS/PreloadJS/blob/master/lib/preloadjs-0.6.2.combined.js#L6352

**Comment by belldandu** [comment]
@attenzione 
I have this issue too now all of the sudden when i decided to rewrite my code. After removing some images. This issue is also on line 13 on the minified version.

From what i can see it is definetly a typo. Why no one caught it until now though is beyond me.
As it only occurs when preload cannot load an image. 

@lannymcnie if i submit a pull request would it be accepted or should i just fix it on my end and wait for you guys to fix it. Cause i'm willing to bet this typo isnt just in the lib directory.

**Comment by wdamien** [comment]
@attenzione and @belldandu Thanks for the report and for offering a fix.  However this has already been fixed. Its currently in the NEXT version @ https://github.com/CreateJS/PreloadJS/blob/master/lib/preloadjs-NEXT.combined.js (or the min version if you prefer).

**Comment by attenzione** [comment]
when NEXT version is planned to become stable and released?

**Comment by lannymcnie** [comment]
@attenzione There are no solid dates yet, sorry! We are hoping to get some big updates in the near future though, stay tuned! The NEXT versions are usually pretty solid though, so there should be no issue using them.
