### ISSUE TITLE
Speed: PreloadJS vs normal header loading

### ISSUE THREAD

**Issue by djangosdk** [CreateJS/PreloadJS#212]
Hi,
I am using PreloadJS to prelaod all of my assets/resources (css,jquery and jquery plugins) in my application.
I have alike 60 jquery plugins and I wanted to load everything in plugin manner.

I noticed loading everthing with PreloadJS is very slow as compared to old fashioned 
```<link>``` and ```<script>``` tags.

I tried setting ```queue.setMaxConnections(100);```` but still same.
Am i doing something wrong ?

**Comment by djangosdk** [comment]
I am having problem setting up tag-based-loading instead of XHR.
I asked a question here. http://stackoverflow.com/questions/39082926/preloadjs-tag-loading-instead-of-xhr

Any help will be much appreciated.

**Comment by lannymcnie** [comment]
@djangosdk Sorry for no response on this -- I didn't see it on SO either.

As far as I know, the difference between XHR and tag-based loading should have no difference in speed. The behaviour is basically the same, XHR just gives you raw data, instead of having the browser control how the information is downloaded.

There are differences in how items are cached, and XHR may re-download each time.

Your sample in StackOverflow is fine -- the way to specify tag-based loading is by passing `false` to the first parameter of LoadQueue.

One big note is that `maxConnections` will not work as expected with scripts by default, since scripts can have load-order dependencies, so only one will be downloaded at a time. You can turn this off by setting `maintainScriptOrder` to false.

I don't believe this is a bug, but feel free to reopen.
