### ISSUE TITLE
preload sound file problem in internet explorer

### ISSUE THREAD

**Issue by s-senguttuvan** [CreateJS/PreloadJS#216]
hi,
i have to preload more than 100 sound files,
works fine in moz,chrome safari,
not working in ie, 
more than 60 sounds also not loading perfectly,
many times not working!!!!

what is the maximum sound files we can load?

**Comment by lannymcnie** [comment]
This is a known issue. We found that 41 seemed to be the magic number.
https://github.com/CreateJS/SoundJS/issues/40

Note that this affects HTML audio only, and not Web Audio, which is why IE is affected (Web Audio APIs were added to Edge).

You could look into Audio sprites, which are supported by SoundJS - which combines multiple audio into one file, and requires less actual audio to be loaded.
http://createjs.com/docs/soundjs/classes/AudioSprite.html

**Comment by sengu90** [comment]
Thanks for your suggestion !!!!
