### ISSUE TITLE
_this is not defined... only on Firefox?

### ISSUE THREAD

**Issue by sortofsleepy** [CreateJS/PreloadJS#233]
Hello!

I see this has been filed as a bug before that sounded like it had been fixed - but unfortunately it seems to have made it's way back. There are also some additional strange errors that might be in relation(see screenshot)

I'm seeing this behavior in Firefox only, Chrome for whatever reason is ok (Safari and IE are not a part of my requirements so I haven't tested them)

I've tried all of the 0.6.2 release libraries both the regular and NEXT versions 😢 

Any ideas on whats wrong? Looking at the unminified source, it looked like a simple mistake, but changing `_this` to `this` results in another strange error.

Trying this on Windows 10 if that happens to affect things.

Help is appreciated!

__After correcting variable__
![preloadjs-bad-fix](https://user-images.githubusercontent.com/308302/28925364-884ce46c-7819-11e7-9fd7-acb8bad9e20f.PNG)

__Before correcting variable__
![preloadjs](https://user-images.githubusercontent.com/308302/28925365-88545cba-7819-11e7-99c2-edd46bb773bc.PNG)

__Line in code where mistake(?) happens__
![preloadjs2](https://user-images.githubusercontent.com/308302/28925366-88547d4e-7819-11e7-84e9-a363b4a826a4.PNG)

**Comment by lannymcnie** [comment]
This issue was resolved in December, 2015 - about a month after the release of 0.6.2 -- so that version (both combined and min) will have that issue.

The approach was changed pass an event instead (March 2017), and the NEXT version reflects that change. You can see it here: https://github.com/CreateJS/PreloadJS/blob/master/lib/preloadjs-NEXT.combined.js#L6844

Hope that helps!
