### ISSUE TITLE
LoadQueue() fires multiple times on firefox 69.0.1 

### ISSUE THREAD

**Issue by Falcikas** [CreateJS/PreloadJS#265]
I have create a fiddle to illustrate the example: 

https://jsfiddle.net/23kot0s7/

Result on Firefox 69.0.1  : 

![image](https://user-images.githubusercontent.com/24302421/65791214-f3d2b980-e169-11e9-8144-c0f1b233744f.png)

Result on Chrome 77.0.3865.90: 

![image](https://user-images.githubusercontent.com/24302421/65791267-0b11a700-e16a-11e9-9c7e-fda2eff1664c.png)

**Comment by lannymcnie** [comment]
This is probably just due to a race condition, and potentially how the browsers handle threading and caching. You are calling loadFile() multiple times, which will append to an open queue, or start a new one. Because you are loading the same file, one of the browsers is returning immediately causing an additional load, the other one has a short delay, resulting in the file getting added to the internal queue. 

If you are loading separate files, it should not happen. 

The best practice is to append to a queue array, and use `loadManifest()` instead one time.

Hope that helps!

**Comment by Falcikas** [comment]
I was loading different files on my local project and still queue callback fired for each file on Firefox, but loading via `loadManifest()` fixed the problem. Thank you for your answer, closing.
